= Java (Debian "Wheezy" Docker Image)

== Introduction
ClassicDriver Docker container with Java installed.

== Name/Tag
The naming strategy will be <organisation>/<os-distribution>-<os-version>-<feature>:<version-tag>.
The 'version-tag' is optional
....
classicdriver/debian-wheezy-java:1.8.60
....

== How to BUILD this image
. Clone the Git repository
+
....
git clone http://<git.host>/docker-debian-wheezy-java.git
....
. Browse to the cloned repository
+
....
cd <parent-folder>
....
. Build the docker image with the command
+
....
docker build --rm=true --tag=classicdriver/debian-wheezy-java:1.8.60 docker-debian-wheezy-java/.
....
. Test the docker image by running the command
+
....
docker run -it --rm=true classicdriver/debian-wheezy-java:1.8.60
....
. The console will be attached to the running container
. Run the following command
+
....
java -version
....
.. The output should be something like the following
+
....
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (...)
....
. Exit the container
